# Generated by Django 5.2.4 on 2025-09-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['created_date']},
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_date',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_date',
            field=models.TimeField(auto_now=True),
        ),
    ]
